base_url_template: "https://www.nhatot.com/mua-ban-bat-dong-san-{city}"
# 59 provinces excluding ha-noi, can-tho, thanh-hoa, da-nang
cities:
  - "tp-ho-chi-minh"
  - "binh-duong"
  - "an-giang"
  - "ba-ria-vung-tau"
  - "bac-giang"
  - "bac-kan"
  - "bac-lieu"
  - "bac-ninh"
  - "ben-tre"
  - "binh-dinh"
  - "binh-phuoc"
  - "binh-thuan"
  - "ca-mau"
  - "cao-bang"
  - "dak-lak"
  - "dak-nong"
  - "dien-bien"
  - "dong-nai"
  - "dong-thap"
  - "gia-lai"
  - "ha-giang"
  - "ha-nam"
  - "ha-tinh"
  - "hai-duong"
  - "hai-phong"
  - "hau-giang"
  - "hoa-binh"
  - "hung-yen"
  - "khanh-hoa"
  - "kien-giang"
  - "kon-tum"
  - "lai-chau"
  - "lam-dong"
  - "lang-son"
  - "lao-cai"
  - "long-an"
  - "nam-dinh"
  - "nghe-an"
  - "ninh-binh"
  - "ninh-thuan"
  - "phu-tho"
  - "phu-yen"
  - "quang-binh"
  - "quang-nam"
  - "quang-ngai"
  - "quang-ninh"
  - "quang-tri"
  - "soc-trang"
  - "son-la"
  - "tay-ninh"
  - "thai-binh"
  - "thai-nguyen"
  - "thua-thien-hue"
  - "tien-giang"
  - "tra-vinh"
  - "tuyen-quang"
  - "vinh-long"
  - "vinh-phuc"
  - "yen-bai"

  

gateway_base: "https://gateway.chotot.com/v1/public/ad-listing/"
max_pages: 200
start_page: 1
db_file: "nhatot.db"
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

column_mapping:
  "ad.list_id": "id"
  "ad.price": "price"
  "ad.price_string": "displayed_price"
  "ad.price_million_per_m2": "price_per_m2"
  "ad.size": "size"
  "ad.size_unit_string": "size_unit"
  "ad.rooms": "bed_rooms"
  "ad.toilets": "toilets"
  "ad_params.house_type.value": "house_type"
  "ad_params.pty_characteristics.value": "property_characteristics"
  "ad.length": "length"
  "ad.width": "width"
  "ad.list_time": "unix_timestamp"
  "ad.is_main_street": "is_main_street"
  "ad_params.property_legal_document.value": "property_legal_document"
  "ad.region_name": "city"
  "ad.area_name": "district"
  "ad.ward_name": "ward"
  "ad.street_name": "street"
  "special:latitude_longitude": "gps"
  "ad_params.address.value": "full_address"